language: cpp

services:
  - docker

sudo: required

env:
  - MATRIX_EVAL="PS2DOCKER=akuhak/ps2toolchain PS2FORK=ps2dev PS2BRANCH=master"

matrix:
  fast_finish: true
  include:
    - env:
      - MATRIX_EVAL="PS2DOCKER=ps2homebrew/ps2toolchain PS2FORK=ps2homebrew PS2BRANCH=test1"
    - env:
      - MATRIX_EVAL="PS2DOCKER=ps2homebrew/gcc5 PS2FORK=ps2homebrew PS2BRANCH=test1"
    - env:
      - MATRIX_EVAL="PS2DOCKER=akuhak/ps2toolchain PS2FORK=ps2dev PS2BRANCH=master"
  allow_failures:
    - env:
      - MATRIX_EVAL="PS2DOCKER=ps2homebrew/ps2toolchain PS2FORK=ps2homebrew PS2BRANCH=test1"

before_install:
    - eval "${MATRIX_EVAL}"

before_script:
  # Get docker image
  - docker pull ${PS2DOCKER}:latest
  - docker ps

  # Run DOCKER, run!
  - docker run -d ${PS2DOCKER} bash -c "while true; do sleep 5; done" > container_id

  # Configure ps2sdk
  - docker exec -t $(cat container_id) bash -c "ls -l"
  - docker exec -t $(cat container_id) bash -c "cd /; git clone https://github.com/${PS2FORK}/ps2sdk -b ${PS2BRANCH}"
  - docker exec -t $(cat container_id) bash -c "cd /ps2sdk/; make install --silent"

# installing ports
  - docker exec -t $(cat container_id) bash -c "cd /; git clone https://github.com/ps2dev/ps2sdk-ports"
  - docker exec -t $(cat container_id) bash -c "cd /ps2sdk-ports/; make libpng libjpeg"

  # installing gsKit
  - docker exec -t $(cat container_id) bash -c "cd /; git clone https://github.com/akuhak/gsKit -b patch-5; cd /gsKit/; make --silent && make --silent install"

  - docker exec -t $(cat container_id) bash -c "mkdir -p /work/;"
  - docker cp $TRAVIS_BUILD_DIR/. $(cat container_id):/work/

script:
  - docker exec -t $(cat container_id) bash -c "cd /work/; make CDSUPPORT=1 NOT_PACKED=1"
  - docker cp $(cat container_id):/work/fceu.elf $TRAVIS_BUILD_DIR/fceu_$TRAVIS_JOB_NUMBER.elf
  - curl --upload-file fceu_$TRAVIS_JOB_NUMBER.elf https://transfer.sh/fceu_$TRAVIS_JOB_NUMBER.elf | grep transfer

deploy:
  provider: releases
  api_key:
    secure: avYeerQDCmDWGhol50l5yggW4xL6Fx+3pqdPL2Pf+/rvdDhI2kL0I1HVCQ8hAUkWksO851XgnnRY+toZ0Q7wEI7F/diJf6mIKmmfaR/4eueK0UaLeOS6OwxZ7cZaHPvqSjlpk2I178t/lyyJN3bdTwMuMYXL7cpphi2B04DbwnlA4mYPREe/qZjY50C+6aY/jlbFSKUZYqgHYM9fmcLp4KU5LNJzYiE9+ll3p+w7zvjAeSCIldY2xtumJCVr2E85tVD3X2Bzhx0Ze89thATuC0z4sGtscTTI7XNhgiTbk2MXdnmPQ9fXUoAdNiTIiZ90cHQmh8eacYA6elhUXBCboDXbDVWMF8yKtngwFjmJLNX6gRqwwzmYgeaMusisPhnWS+Xu8Uf718LS1yp+BjETxTjUda1Utpj+8NbM+WFBXd0squrLkxRoxE946IyP/w4iPpXQh3sFKk+ftvnl9B8LujBK8W9q7uPpEGzXTr9xSa52i+LVsa9DqP+PIt6GpQL6kpu9pVWdBGRsHlRFLtdd3VL9ehZ6/JRHKkeFyfm3be5sSon5CzXp+7IF6/vcifNYURcwbmsniuhOl/EX5S0DgmScQhNw45+gZ4l/Cnvrm96FLV7ZrfhUelTRUCMcaX5Bvf/P4yZy7lN7iqxzB39ujxI737Fy3N03Eszt0CEXr4s=
  file: "$TRAVIS_BUILD_DIR/fceu_$TRAVIS_JOB_NUMBER.elf"
  skip_cleanup: true
  on:
    tags: true
    branch: master
